export const CONTACT_SECTION_DEFAULT_WIDTH = 300;
export const CONTACT_SECTION_MIN_WIDTH = 200;
export const CONTACT_SECTION_MAX_WIDTH = 400;
export const RESIZABLE_WIDTH = 10;

export const THREAD_WINDOW_DEFAULT_WIDTH = 500;
export const THREAD_WINDOW_MIN_WIDTH = 400;
export const THREAD_WINDOW_MAX_WIDTH = 800;

export const SECTION_TITLE_HEIGHT = 50;
export const SECTION_END_HEIGHT = 60;

export const CONTACT_SECTION_FONT_COLOR = "#FFFFFF";
export const CONTACT_SECTION_BACKGROUND_COLOR = "#17324C";
export const CONTACT_SECTION_END_BACKGROUND_COLOR = "#112538";
export const CONTACT_SECTION_SPLITTER_BACKGROUND_COLOR = "#3775B0";

export const CONTACT_SECTION_SELECTED_BACKGROUND_COLOR = "#24A9DB";
export const CONTACT_SECTION_HOVER_BACKGROUND_COLOR = "#3775B0";

export const CHAT_SECTION_HEADER_BACKGROUND_COLOR = "#295b89";
export const CHAT_SECTION_SPLITTER_BACKGROUND_COLOR = "#D9D9D9";

export const PEOPLE_STATUS_ACTIVE_COLOR = "#26BF36";
export const PEOPLE_STATUS_AWAY_COLOR = "#FFCC66";
export const PEOPLE_STATUS_BUSY_COLOR = "#D94848";
export const PEOPLE_STATUS_OFFLINE_COLOR = "#888888";

export const FONT_BLACK_COLOR = "#000000";
export const FONT_GREY_COLOR = "#AAAAAA";

export const BACKGROUND_DEEP_LIGHT_GREY_COLOR = "#EEEEEE";