export const DEFAULT_CONTACT_SECTION_WIDTH = 300;
export const CONTACT_SECTION_MIN_WIDTH = 200;
export const CONTACT_SECTION_MAX_WIDTH = 400;
export const RESIZABLE_WIDTH = 10;

export const SECTION_TITLE_HEIGHT = 60;
export const SECTION_END_HEIGHT = 60;

export const CONTACT_SECTION_FONT_COLOR = "#FFFFFF";
export const CONTACT_SECTION_BACKGROUND_COLOR = "#17324C";
export const CONTACT_SECTION_END_BACKGROUND_COLOR = "#112538";
export const CONTACT_SECTION_SPLITTER_BACKGROUND_COLOR = "#3775B0";

export const CONTACT_SECTION_SELECTED_BACKGROUND_COLOR = "#24A9DB";
export const CONTACT_SECTION_HOVER_BACKGROUND_COLOR = "#3775B0";

export const CHAT_SECTION_HEADER_BACKGROUND_COLOR = "#295b89";

export const PEOPLE_STATUS_ACTIVE_COLOR = "#26BF36";
export const PEOPLE_STATUS_AWAY_COLOR = "#FFCC66";
export const PEOPLE_STATUS_BUSY_COLOR = "#D94848";
export const PEOPLE_STATUS_OFFLINE_COLOR = "#888888";